/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OauthSessionEndedRouteImport } from './routes/oauth/session-ended'
import { Route as OauthConsentRouteImport } from './routes/oauth/consent'

const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthSessionEndedRoute = OauthSessionEndedRouteImport.update({
  id: '/oauth/session-ended',
  path: '/oauth/session-ended',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/signin': typeof SigninRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/oauth/session-ended': typeof OauthSessionEndedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/signin': typeof SigninRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/oauth/session-ended': typeof OauthSessionEndedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/signin': typeof SigninRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/oauth/session-ended': typeof OauthSessionEndedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/signin'
    | '/verify-otp'
    | '/oauth/consent'
    | '/oauth/session-ended'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/signin'
    | '/verify-otp'
    | '/oauth/consent'
    | '/oauth/session-ended'
  id:
    | '__root__'
    | '/'
    | '/callback'
    | '/signin'
    | '/verify-otp'
    | '/oauth/consent'
    | '/oauth/session-ended'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallbackRoute: typeof CallbackRoute
  SigninRoute: typeof SigninRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
  OauthConsentRoute: typeof OauthConsentRoute
  OauthSessionEndedRoute: typeof OauthSessionEndedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/session-ended': {
      id: '/oauth/session-ended'
      path: '/oauth/session-ended'
      fullPath: '/oauth/session-ended'
      preLoaderRoute: typeof OauthSessionEndedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallbackRoute: CallbackRoute,
  SigninRoute: SigninRoute,
  VerifyOtpRoute: VerifyOtpRoute,
  OauthConsentRoute: OauthConsentRoute,
  OauthSessionEndedRoute: OauthSessionEndedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
